### ISSUE TITLE
Script error with 'playlist to channel.py'

### ISSUE THREAD

**Issue by irodimus** [nwithan8/dizqueTV-python#110]
I'm using:
```
PlexAPI 4.15.14
dizqueTV-python 1.5.3.1
Python 3.12.4
dizqueTV 1.5.3
```
When running 'playlist to channel.py script, I get this error:
```
Traceback (most recent call last):
  File "/Applications/Plex Scripts/Scripts/dizqueTV-scripts/scripts/basic/playlist_to_channel.py", line 10, in <module>
    from dizqueTV import API
  File "/usr/local/lib/python3.12/site-packages/dizqueTV/__init__.py", line 1, in <module>
    from dizqueTV.dizquetv import (API,
  File "/usr/local/lib/python3.12/site-packages/dizqueTV/dizquetv.py", line 15, in <module>
    import dizqueTV.helpers as helpers
  File "/usr/local/lib/python3.12/site-packages/dizqueTV/helpers.py", line 15, in <module>
    from dizqueTV.exceptions import MissingSettingsError
  File "/usr/local/lib/python3.12/site-packages/dizqueTV/exceptions.py", line 5, in <module>
    from dizqueTV._info import __version__ as version
ImportError: cannot import name '__version__' from 'dizqueTV._info' (/usr/local/lib/python3.12/site-packages/dizqueTV/_info.py)
```
This used to work for a couple of months. Any ideas where the issue could be? Please let me know if you need more information.

**Comment by nwithan8** [comment]
Fixed in v1.5.3.2, thanks for reporting.
