### ISSUE TITLE
sort_programs_randomly not working

### ISSUE THREAD

**Issue by psybertech** [nwithan8/dizqueTV-python#22]
Hey there.

This method doesn't work for me: 
channel.sort_programs_randomly()

channel.sort_programs_by_release_date(), channel.sort_programs_by_duration() and channel.sort_programs_alphabetically() worked fine.

When trying, channel.sort_programs_randomly(), it just ends up removing everything from the channel and then errors out:

Traceback (most recent call last):
  File "shuffle_test.py", line 11, in <module>
    channel.sort_programs_randomly()
  File "/usr/local/lib/python3.8/dist-packages/dizqueTV/helpers.py", line 23, in inner
    return func(obj, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dizqueTV/channels.py", line 319, in sort_programs_randomly
    return self.add_programs(programs=sorted_programs)
  File "/usr/local/lib/python3.8/dist-packages/dizqueTV/helpers.py", line 23, in inner
    return func(obj, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dizqueTV/channels.py", line 228, in add_programs
    for program in programs:
TypeError: 'NoneType' object is not iterable

Thanks
J

**Comment by nwithan8** [comment]
Bug was corrected in recent commit. Will be included in upcoming 0.0.70 release
